version: '3'

services:
    neo4j:
      image: neo4j:4.4-community
      ports:
        - 7474:7474
        - 7373:7373
        - 7687:7687
      environment: 
        - NEO4J_AUTH
      healthcheck:
        test: curl --fail http://localhost:7474 || exit 1
        interval: 30s
        retries: 5
        start_period: 20s
        timeout: 10s
