name: ontolocy-examples-environment
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pip
  - pip:
      - ontolocy>=0.8
      - networkx
      - ipydatagrid
      - ipysigma
      - yfiles_jupyter_graphs
